name: cracker
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4

  provider: ^4.3.3
  share: ^0.6.5+4
  flutter_spinkit: ^4.0.0
  flutter_screenutil: ^5.0.1+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  settings_ui:
  url_launcher:
  awesome_dialog: ^2.1.1
  rating_dialog: ^2.0.1
  custom_switch: ^0.0.1
  list_tile_switch: ^1.0.0
  flutter_fortune_wheel: ^1.1.1
  flutter_spinwheel: ^0.1.0
  flutter_spinning_wheel: ^1.1.0
  carousel_slider: ^4.0.0
  firebase_database: ^3.1.6
  adaptive_theme: ^2.3.0
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
  flutter_lints: ^1.0.0
# The following section is specific to Flutter.

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.png"
  
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/images/login.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/signup.png
    - assets/images/forgotpassword.png
    - assets/images/newpassword.png
    - assets/images/sslight.png
    - assets/images/caesar1.png
    - assets/images/caesar2.png
    - assets/images/caesar3.png
    - assets/images/caesar4.png
    - assets/images/clip2.png
    - assets/images/logotext.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
